services:
  backend:
    build:
      context: ./backend
    container_name: smart-receipt-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/smart_receipt_db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: smart-receipt-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    container_name: smart-receipt-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smart_receipt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: